import { constants } from "node:fs";
import { execFile } from "node:child_process";
import {
  access,
  chmod,
  copyFile,
  cp,
  lstat,
  mkdir,
  readFile,
  rename,
  rm,
  stat,
  writeFile
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { detectAllReviewerAdapters } from "./reviewer-adapter.mjs";
import { createCodexHost } from "./codex-host.mjs";
import { initializeControlStore } from "./control-store.mjs";
import { SCHEMA_VERSION } from "./schema.mjs";

const SRC_DIR = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(SRC_DIR, "..");
const TEMPLATE_ROOT = path.join(PACKAGE_ROOT, "templates");
const RUNTIME_VERSION = "0.7.6";

const CODEX_MARKER_START = "# agent-feedback-loop:start";
const CODEX_MARKER_END = "# agent-feedback-loop:end";
const LEGACY_RECONCILE_LABEL = "io.github.super3ben.agent-feedback-loop.reconcile";
const LEGACY_CLEANUP_TIMEOUT_MS = 5_000;

// Declarative CLI registry. Adding a new model-visible CLI = adding one entry.
// configKey/configPath are resolved against home in pathsFor.
const CLIS = [
  {
    id: "codex",
    label: "Codex",
    format: "toml",
    configKey: "codexConfig",
    configPath: [".codex", "config.toml"],
    hookEvent: "UserPromptSubmit",
    hookArgs: ["--event", "UserPromptSubmit", "--cli", "codex", "--continue"],
    legacyStopEvent: "Stop",
    hookTimeout: 5,
    timeoutUnit: "seconds"
  },
  {
    id: "claude",
    label: "Claude Code",
    format: "json",
    configKey: "claudeSettings",
    configPath: [".claude", "settings.json"],
    hookEvent: "UserPromptSubmit",
    hookArgs: ["--event", "UserPromptSubmit", "--cli", "claude"],
    legacyStopEvent: "Stop",
    hookTimeout: 5,
    timeoutUnit: "seconds"
  },
  {
    id: "gemini",
    label: "Gemini CLI",
    format: "json",
    configKey: "geminiSettings",
    configPath: [".gemini", "settings.json"],
    hookEvent: "BeforeAgent",
    hookArgs: ["--event", "BeforeAgent", "--cli", "gemini"],
    legacyStopEvent: "AfterAgent",
    hookTimeout: 5000,
    timeoutUnit: "milliseconds"
  }
];

export function pathsFor(home = os.homedir()) {
  const packRoot = path.join(home, ".agent", "feedback-loop");
  const runtimeRoot = path.join(packRoot, "versions", RUNTIME_VERSION);
  const dataRoot = path.join(home, ".agent", "feedback-loop-data");
  const keyRoot = path.join(home, ".agent", "feedback-loop-keys");
  const legacyDatabase = path.join(dataRoot, "store", "feedback-loop.sqlite3");
  const paths = {
    home,
    packRoot,
    runtimeRoot,
    runtimeLauncher: path.join(packRoot, "bin", "afl-hook"),
    runtimeCurrent: path.join(packRoot, "current.json"),
    dataRoot,
    keyRoot,
    controlDatabase: path.join(dataRoot, "store", "control.sqlite3"),
    legacyDatabase,
    storeFile: legacyDatabase,
    blobRoot: path.join(dataRoot, "blobs", "sha256"),
    safetyProjection: path.join(dataRoot, "safety", "guard.json.mac"),
    exportsRoot: path.join(dataRoot, "exports"),
    promptFile: path.join(packRoot, "prompts", "reflection-agent.md"),
    ruleFile: path.join(packRoot, "rules", "feedback-loop.md"),
    reviewerSchema: path.join(packRoot, "schemas", "reviewer-result.schema.json"),
    geminiReviewerPolicy: path.join(packRoot, "policies", "gemini-reviewer-deny-all.toml"),
    geminiReviewerSettings: path.join(packRoot, "settings", "gemini-reviewer.json"),
    coreHook: path.join(packRoot, "hooks", "core-hook.sh"),
    // Generated by older local test syncs, no longer part of the installed
    // prompt pack. Remove it on upgrade so stale tests do not reference
    // deleted per-CLI hooks.
    stalePackEntries: [
      path.join(packRoot, "tests")
    ],
    // Per-CLI hooks from <=0.1.x, replaced by the single core-hook.sh.
    // Deleted on install/uninstall so stale copies can't confuse the model.
    legacyHooks: [
      path.join(packRoot, "hooks", "codex-hook.sh"),
      path.join(packRoot, "hooks", "claude-hook.sh"),
      path.join(packRoot, "hooks", "stop-hook.sh"),
      path.join(packRoot, "hooks", "trigger-rules.sh")
    ]
  };
  for (const cli of CLIS) {
    paths[cli.configKey] = path.join(home, ...cli.configPath);
  }
  return paths;
}

export function runtimeCapability({ nodeVersion = process.versions.node } = {}) {
  const [major, minor] = String(nodeVersion).split(".").map(Number);
  const supported = major > 24 || (major === 24 && minor >= 15);
  return {
    backend: "node:sqlite",
    minimumNode: "24.15.0",
    nodeVersion: String(nodeVersion),
    status: supported ? "configured_unverified" : "unavailable",
    reason: supported
      ? "node:sqlite backend can be checked by live doctor"
      : "Node 24.15 or newer is required for the transactional backend"
  };
}

// Full shell command a CLI config should invoke for the prompt-time hook.
function shellArgument(value) {
  return `'${String(value).replaceAll("'", `'"'"'`)}'`;
}

function hookCommand(paths, cli) {
  return [paths.coreHook, ...cli.hookArgs].map(shellArgument).join(" ");
}

function writeRuntimeLauncher(paths, dryRun, actions) {
  const target = paths.runtimeLauncher;
  actions.push(`write stable launcher -> ${target}`);
  if (dryRun) return;
  const resolver = "const fs=require('fs');const path=require('path');const current=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));const root=path.resolve(current.runtimeRoot);const versions=path.resolve(process.argv[2],'versions')+path.sep;if(!root.startsWith(versions))throw new Error('runtimeRoot is outside managed versions');process.stdout.write(root);";
  const launcher = `#!/bin/sh\nset -eu\nruntime_root="$(${JSON.stringify(process.execPath)} -e ${JSON.stringify(resolver)} ${JSON.stringify(paths.runtimeCurrent)} ${JSON.stringify(paths.packRoot)})"\nexec ${JSON.stringify(process.execPath)} "$runtime_root/bin/agent-feedback-loop.mjs" "$@"\n`;
  return mkdir(path.dirname(target), { recursive: true, mode: 0o700 })
    .then(() => writeFile(target, launcher, { mode: 0o700 }))
    .then(() => chmod(target, 0o700));
}

async function exists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function ensureSafeInstallRoot(home, directory, label, { create }) {
  const relative = path.relative(home, directory);
  if (!relative || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error(`${label} must be a child of the selected home directory`);
  }
  let current = home;
  for (const segment of relative.split(path.sep)) {
    current = path.join(current, segment);
    let info;
    try {
      info = await lstat(current);
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
      if (!create) return;
      await mkdir(current, { mode: 0o700 });
      info = await lstat(current);
    }
    if (info.isSymbolicLink()) throw new Error(`${label} path must not contain a symlink: ${current}`);
    if (!info.isDirectory()) throw new Error(`${label} path component must be a directory: ${current}`);
    if (typeof process.getuid === "function" && info.uid !== process.getuid()) {
      throw new Error(`${label} path must be owned by the current user: ${current}`);
    }
  }
  if (create) await chmod(directory, 0o700);
}

async function validateInstallRoots(paths, dryRun) {
  const options = { create: !dryRun };
  await ensureSafeInstallRoot(paths.home, paths.packRoot, "runtime root", options);
  await ensureSafeInstallRoot(paths.home, paths.dataRoot, "data root", options);
  await ensureSafeInstallRoot(paths.home, paths.keyRoot, "key root", options);
}

function timestamp() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return [
    d.getFullYear(),
    pad(d.getMonth() + 1),
    pad(d.getDate()),
    pad(d.getHours()),
    pad(d.getMinutes()),
    pad(d.getSeconds())
  ].join("");
}

async function backup(file, dryRun, actions) {
  if (!(await exists(file))) return null;
  const target = `${file}.backup-${timestamp()}`;
  actions.push(`backup ${file} -> ${target}`);
  if (!dryRun) await copyFile(file, target);
  return target;
}

function tomlString(value) {
  return JSON.stringify(value);
}

function cleanLegacyCodexHooks(text, paths) {
  const lines = text.split(/\r?\n/)
    .filter((line) => line.trim() !== CODEX_MARKER_START && line.trim() !== CODEX_MARKER_END);
  const blocks = [{ header: null, lines: [] }];
  for (const line of lines) {
    const header = line.trim();
    if (/^\[\[[^\]]+\]\]$/.test(header) || /^\[[^\]]+\]$/.test(header)) {
      blocks.push({ header, lines: [line] });
    } else {
      blocks.at(-1).lines.push(line);
    }
  }

  const managedPaths = [
    paths.coreHook,
    paths.promptFile,
    ...["codex-hook.sh", "claude-hook.sh", "stop-hook.sh"]
      .map((name) => path.join(paths.packRoot, "hooks", name))
  ];
  const managedHandler = (block) => {
    const targets = block.lines
      .map((line) => line.match(/^\s*(?:command|prompt)\s*=\s*(.+?)\s*$/)?.[1])
      .filter(Boolean);
    return targets.some((target) => managedPaths.some((managedPath) => target.includes(managedPath)));
  };
  const cleaned = [];
  for (let index = 0; index < blocks.length;) {
    const block = blocks[index];
    const parent = block.header?.match(/^\[\[hooks\.([^.\]]+)\]\]$/);
    if (!parent) {
      if (!block.header?.match(/^\[\[hooks\.[^.\]]+\.hooks\]\]$/) || !managedHandler(block)) cleaned.push(block);
      index += 1;
      continue;
    }

    const handlerHeader = `[[hooks.${parent[1]}.hooks]]`;
    let next = index + 1;
    const handlers = [];
    while (next < blocks.length && blocks[next].header === handlerHeader) {
      handlers.push(blocks[next]);
      next += 1;
    }
    const remainingHandlers = handlers.filter((handler) => !managedHandler(handler));
    const removedManagedHandler = remainingHandlers.length !== handlers.length;
    if (!removedManagedHandler || remainingHandlers.length > 0) {
      cleaned.push(block, ...remainingHandlers);
    }
    index = next;
  }

  return cleaned.flatMap((block) => block.lines)
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();
}

function defaultLegacySchedulerHost() {
  return {
    bootout({ domain, label }) {
      return new Promise((resolve) => {
        execFile("launchctl", ["bootout", `${domain}/${label}`], {
          timeout: LEGACY_CLEANUP_TIMEOUT_MS,
          killSignal: "SIGKILL"
        }, () => resolve());
      });
    }
  };
}

async function boundedBestEffort(operation, timeoutMs = LEGACY_CLEANUP_TIMEOUT_MS) {
  let timer;
  try {
    await Promise.race([
      Promise.resolve().then(operation).catch(() => {}),
      new Promise((resolve) => { timer = setTimeout(resolve, timeoutMs); })
    ]);
  } finally {
    clearTimeout(timer);
  }
}

async function cleanupLegacyScheduler({ home, platform, dryRun, activate, host }) {
  if (platform !== "darwin" || dryRun) return;
  const plistFile = path.join(home, "Library", "LaunchAgents", `${LEGACY_RECONCILE_LABEL}.plist`);
  if (activate) {
    const domain = `gui/${typeof process.getuid === "function" ? process.getuid() : 0}`;
    await boundedBestEffort(() => host.bootout({ domain, label: LEGACY_RECONCILE_LABEL, plistFile }));
  }
  try {
    const parent = await lstat(path.dirname(plistFile));
    const file = await lstat(plistFile);
    const owned = typeof process.getuid !== "function" || (parent.uid === process.getuid() && file.uid === process.getuid());
    if (!parent.isSymbolicLink() && parent.isDirectory() && !file.isSymbolicLink() && file.isFile() && owned) {
      await rm(plistFile, { force: true });
    }
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}

function codexHookBlock(paths, cli) {
  return [
    CODEX_MARKER_START,
    `[[hooks.${cli.hookEvent}]]`,
    "",
    `[[hooks.${cli.hookEvent}.hooks]]`,
    'type = "command"',
    `command = ${tomlString(hookCommand(paths, cli))}`,
    `timeout = ${cli.hookTimeout}`,
    'statusMessage = "Injecting feedback reflection prompt"',
    CODEX_MARKER_END
  ].join("\n");
}

// Remove our managed entries for a given JSON-config CLI (Claude/Gemini).
// Cleans both the prompt-time hook and AFL-owned legacy post-turn entries,
// matching our hook paths plus legacy per-CLI hook commands.
function removeJsonHookEntries(settings, paths, cli) {
  const isOurs = (hook) => {
    const command = typeof hook.command === "string" ? hook.command : "";
    const prompt = typeof hook.prompt === "string" ? hook.prompt : "";
    return command.includes(paths.coreHook)
      || command.includes(path.join(paths.packRoot, "hooks", "stop-hook.sh"))
      || command.includes("codex-hook.sh")
      || command.includes("claude-hook.sh")
      || prompt.includes(paths.promptFile);
  };
  for (const event of [cli.hookEvent, cli.legacyStopEvent]) {
    const hooks = settings.hooks?.[event];
    if (!Array.isArray(hooks)) continue;
    settings.hooks[event] = hooks
      .map((entry) => {
        if (!entry || !Array.isArray(entry.hooks)) return entry;
        return { ...entry, hooks: entry.hooks.filter((hook) => !isOurs(hook)) };
      })
      .filter((entry) => !entry || !Array.isArray(entry.hooks) || entry.hooks.length > 0);
  }
  return settings;
}

async function readJsonSettings(file) {
  if (!(await exists(file))) return {};
  const text = await readFile(file, "utf8");
  if (!text.trim()) return {};
  return JSON.parse(text);
}

async function removeLegacyHooks(paths, dryRun, actions) {
  for (const file of paths.legacyHooks) {
    if (!(await exists(file))) continue;
    actions.push(`remove legacy hook ${file}`);
    if (!dryRun) await rm(file, { force: true });
  }
}

async function removeStalePromptPackEntries(paths, dryRun, actions) {
  for (const entry of paths.stalePackEntries) {
    if (!(await exists(entry))) continue;
    actions.push(`remove stale tests ${entry}`);
    if (!dryRun) await rm(entry, { recursive: true, force: true });
  }
}

async function writePromptPack(paths, dryRun, actions) {
  actions.push(`copy templates -> ${paths.packRoot}`);
  if (dryRun) {
    await removeStalePromptPackEntries(paths, dryRun, actions);
    await removeLegacyHooks(paths, dryRun, actions);
    return;
  }
  await mkdir(path.dirname(paths.packRoot), { recursive: true });
  await cp(TEMPLATE_ROOT, paths.packRoot, { recursive: true });
  await mkdir(paths.runtimeRoot, { recursive: true, mode: 0o700 });
  await chmod(paths.runtimeRoot, 0o700);
  await cp(path.join(PACKAGE_ROOT, "bin"), path.join(paths.runtimeRoot, "bin"), { recursive: true });
  await cp(path.join(PACKAGE_ROOT, "src"), path.join(paths.runtimeRoot, "src"), { recursive: true });
  await chmod(path.join(paths.runtimeRoot, "bin", "agent-feedback-loop.mjs"), 0o755);
  await mkdir(paths.dataRoot, { recursive: true, mode: 0o700 });
  await chmod(paths.dataRoot, 0o700);
  await mkdir(paths.keyRoot, { recursive: true, mode: 0o700 });
  await chmod(paths.keyRoot, 0o700);
  await mkdir(path.dirname(paths.runtimeCurrent), { recursive: true, mode: 0o700 });
  const currentPayload = `${JSON.stringify({
    runtimeVersion: RUNTIME_VERSION,
    runtimeRoot: paths.runtimeRoot,
    schemaVersion: SCHEMA_VERSION,
    capability: runtimeCapability(),
    installedAt: new Date().toISOString()
  }, null, 2)}\n`;
  const currentTemp = `${paths.runtimeCurrent}.${process.pid}.${Date.now()}.tmp`;
  await writeFile(currentTemp, currentPayload, { mode: 0o600, flag: "wx" });
  await chmod(currentTemp, 0o600);
  await rename(currentTemp, paths.runtimeCurrent);
  await chmod(paths.runtimeCurrent, 0o600);
  await chmod(paths.coreHook, 0o755);
  await removeStalePromptPackEntries(paths, dryRun, actions);
  // cp does not delete files absent from templates, so pre-0.2 per-CLI hooks
  // linger after an upgrade. Remove them explicitly.
  await removeLegacyHooks(paths, dryRun, actions);
}

async function installTomlBlock(paths, cli, dryRun, actions) {
  const configFile = paths[cli.configKey];
  await backup(configFile, dryRun, actions);
  const current = (await exists(configFile)) ? await readFile(configFile, "utf8") : "";
  const cleaned = cleanLegacyCodexHooks(current, paths);
  const block = codexHookBlock(paths, cli);
  const next = `${cleaned.trimEnd()}${cleaned.trim() ? "\n\n" : ""}${block}\n`;
  actions.push(`connect ${cli.label} hook -> ${paths.coreHook}`);
  if (!dryRun) {
    await mkdir(path.dirname(configFile), { recursive: true });
    await writeFile(configFile, next, "utf8");
  }
}

async function installJsonHooks(paths, cli, dryRun, actions) {
  const configFile = paths[cli.configKey];
  await backup(configFile, dryRun, actions);
  const settings = removeJsonHookEntries(await readJsonSettings(configFile), paths, cli);
  settings.hooks = settings.hooks || {};
  settings.hooks[cli.hookEvent] = settings.hooks[cli.hookEvent] || [];
  settings.hooks[cli.hookEvent].push({
    matcher: "",
    hooks: [{ type: "command", command: hookCommand(paths, cli), timeout: cli.hookTimeout }]
  });
  actions.push(`connect ${cli.label} hook -> ${paths.coreHook}`);
  if (!dryRun) {
    await mkdir(path.dirname(configFile), { recursive: true });
    await writeFile(configFile, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
  }
}

async function installCli(paths, cli, dryRun, actions) {
  if (cli.format === "toml") {
    await installTomlBlock(paths, cli, dryRun, actions);
  } else {
    await installJsonHooks(paths, cli, dryRun, actions);
  }
}

export async function install(options = {}) {
  const home = options.home || os.homedir();
  const dryRun = Boolean(options.dryRun);
  const capability = runtimeCapability({ nodeVersion: options.nodeVersion || process.versions.node });
  if (capability.status === "unavailable") throw new Error(capability.reason);
  const paths = pathsFor(home);
  const actions = [];
  await cleanupLegacyScheduler({
    home,
    platform: options.platform || process.platform,
    dryRun,
    activate: options.activateLegacySchedulerCleanup ?? (path.resolve(home) === path.resolve(os.homedir())),
    host: options.legacySchedulerHost || options.schedulerHost || defaultLegacySchedulerHost()
  });
  await validateInstallRoots(paths, dryRun);
  if (!dryRun) {
    const controlStore = initializeControlStore({ paths });
    controlStore.close();
  }
  await writePromptPack(paths, dryRun, actions);
  await writeRuntimeLauncher(paths, dryRun, actions);
  for (const cli of CLIS) {
    await installCli(paths, cli, dryRun, actions);
  }
  let codex = { available: false, configured: dryRun, runnable: false, status: dryRun ? "dry_run" : "unavailable" };
  if (!dryRun) {
    const cli = CLIS.find((entry) => entry.id === "codex");
    const codexHost = options.codexHost || createCodexHost({ version: RUNTIME_VERSION });
    codex = await codexHost.synchronize({
      home,
      cwd: options.cwd || process.cwd(),
      promptCommand: hookCommand(paths, cli)
    });
    if (codex.runnable) {
      actions.push(`Codex prompt hook verified for a newly spawned app-server via ${codex.hostCommand || "host inspector"}`);
    } else {
      actions.push(`Codex hooks configured but not runnable (${codex.status}${codex.reason ? `: ${codex.reason}` : ""})`);
    }
  }
  return { dryRun, paths, actions, codex };
}

async function uninstallCli(paths, cli, dryRun, actions) {
  const configFile = paths[cli.configKey];
  if (!(await exists(configFile))) return;
  await backup(configFile, dryRun, actions);
  if (cli.format === "toml") {
    const current = await readFile(configFile, "utf8");
    const next = `${cleanLegacyCodexHooks(current, paths)}\n`;
    actions.push(`disconnect ${cli.label} hook`);
    if (!dryRun) await writeFile(configFile, next, "utf8");
  } else {
    const settings = removeJsonHookEntries(await readJsonSettings(configFile), paths, cli);
    actions.push(`disconnect ${cli.label} hook`);
    if (!dryRun) await writeFile(configFile, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
  }
}

export async function uninstall(options = {}) {
  const home = options.home || os.homedir();
  const dryRun = Boolean(options.dryRun);
  const removeFiles = Boolean(options.removeFiles);
  const paths = pathsFor(home);
  const actions = [];

  await cleanupLegacyScheduler({
    home,
    platform: options.platform || process.platform,
    dryRun,
    activate: options.activateLegacySchedulerCleanup ?? (path.resolve(home) === path.resolve(os.homedir())),
    host: options.legacySchedulerHost || options.schedulerHost || defaultLegacySchedulerHost()
  });

  for (const cli of CLIS) {
    await uninstallCli(paths, cli, dryRun, actions);
  }
  if (removeFiles) {
    actions.push(`remove ${paths.packRoot}`);
    if (!dryRun) {
      await rm(paths.packRoot, { recursive: true, force: true });
      await rm(paths.runtimeRoot, { recursive: true, force: true });
    }
  } else {
    await removeLegacyHooks(paths, dryRun, actions);
  }

  return { dryRun, paths, actions };
}

async function isExecutable(file) {
  try {
    await access(file, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

export async function doctor(options = {}) {
  const home = options.home || os.homedir();
  const paths = pathsFor(home);

  const files = {
    prompt: await exists(paths.promptFile),
    rule: await exists(paths.ruleFile),
    runtimeLauncher: await exists(paths.runtimeLauncher),
    runtimeCurrent: await exists(paths.runtimeCurrent),
    coreHook: await exists(paths.coreHook),
    coreHookExecutable: await isExecutable(paths.coreHook)
  };
  let runtime = { selected: false, expectedVersion: RUNTIME_VERSION, expectedSchemaVersion: SCHEMA_VERSION };
  try {
    const current = JSON.parse(await readFile(paths.runtimeCurrent, "utf8"));
    runtime = {
      ...runtime,
      selected: current.runtimeVersion === RUNTIME_VERSION
        && path.resolve(current.runtimeRoot) === path.resolve(paths.runtimeRoot)
        && Number(current.schemaVersion) === SCHEMA_VERSION,
      runtimeVersion: current.runtimeVersion,
      runtimeRoot: current.runtimeRoot,
      schemaVersion: current.schemaVersion
    };
  } catch (error) {
    runtime.reason = error.message;
  }
  files.runtimeSelected = runtime.selected;

  const clis = {};
  for (const cli of CLIS) {
    const configFile = paths[cli.configKey];
    if (cli.format === "toml") {
      const text = (await exists(configFile)) ? await readFile(configFile, "utf8") : "";
      const promptConnected = text.includes(paths.coreHook);
      const legacyStopPresent = text.includes(path.join(paths.packRoot, "hooks", "stop-hook.sh"));
      const configured = promptConnected;
      const codexHost = options.codexHost || createCodexHost({ version: RUNTIME_VERSION });
      const host = await codexHost.inspect({
        home,
        cwd: options.cwd || process.cwd(),
        promptCommand: hookCommand(paths, cli)
      });
      const runnable = configured && host.runnable;
      clis[cli.id] = {
        connected: runnable,
        configured,
        runnable,
        promptConnected: configured && Boolean(host.prompt?.runnable),
        promptConfigured: promptConnected,
        legacyStopPresent,
        promptTrustStatus: host.prompt?.trustStatus || "unknown",
        status: host.status,
        hostAvailable: host.available,
        hostCommand: host.hostCommand,
        inspectionScope: host.inspectionScope || "spawned_app_server",
        activeDesktopState: host.activeDesktopState || "not_observed",
        reason: host.reason,
        managedBlock: text.includes(CODEX_MARKER_START)
      };
    } else {
      let settings = {};
      try {
        settings = await readJsonSettings(configFile);
      } catch {
        settings = {};
      }
      const cmds = (event) => (Array.isArray(settings.hooks?.[event])
        ? settings.hooks[event].flatMap((entry) => (Array.isArray(entry.hooks) ? entry.hooks : []))
        : []).map((hook) => (typeof hook.command === "string" ? hook.command : ""));
      const promptConnected = cmds(cli.hookEvent).some((c) => c.includes(paths.coreHook));
      const legacyStopPresent = cmds(cli.legacyStopEvent).some((c) => c.includes(path.join(paths.packRoot, "hooks", "stop-hook.sh")));
      clis[cli.id] = {
        connected: promptConnected,
        configured: promptConnected,
        runnable: promptConnected,
        promptConnected,
        legacyStopPresent
      };
    }
  }

  const capability = runtimeCapability();
  const reviewerDetector = options.reviewerDetector || detectAllReviewerAdapters;
  const reviewers = await reviewerDetector();
  const readyClis = [];
  const unavailableClis = [];
  for (const cli of CLIS) {
    const reviewer = reviewers[cli.id] || { cli: cli.id, available: false, executable: null };
    const operational = Boolean(clis[cli.id].runnable && reviewer.available);
    clis[cli.id] = {
      ...clis[cli.id],
      reviewerAvailable: Boolean(reviewer.available),
      reviewerExecutable: reviewer.executable || reviewer.command || null,
      operational
    };
    if (operational) readyClis.push(cli.id);
    else unavailableClis.push(cli.id);
  }
  const healthy = Object.values(files).every(Boolean)
    && CLIS.every((cli) => clis[cli.id].runnable)
    && readyClis.length > 0;
  const degraded = unavailableClis.length > 0;
  const legacyStopRemoved = CLIS.every((cli) => !clis[cli.id].legacyStopPresent);
  const reflectionDirectoryPath = path.join(options.cwd || process.cwd(), ".agent", "reflections");
  return {
    healthy,
    degraded,
    home,
    files,
    promptHook: { configured: CLIS.every((cli) => clis[cli.id].configured), runnable: CLIS.every((cli) => clis[cli.id].runnable) },
    controlStore: { path: paths.controlDatabase, exists: await exists(paths.controlDatabase) },
    reflectionDirectory: { path: reflectionDirectoryPath, exists: await exists(reflectionDirectoryPath) },
    reviewerProvider: reviewers,
    legacyStopRemoved,
    runtime,
    clis,
    reviewers,
    operational: { readyClis, unavailableClis },
    capability,
    dataRoot: paths.dataRoot,
    keyRoot: paths.keyRoot
  };
}

export async function assertTemplateTree() {
  await stat(TEMPLATE_ROOT);
}
