import { constants } from "node:fs";
import {
  access,
  chmod,
  copyFile,
  cp,
  lstat,
  mkdir,
  readFile,
  rename,
  rm,
  stat,
  writeFile
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { detectAllReviewerAdapters } from "./reviewer-adapter.mjs";
import { createCodexHost } from "./codex-host.mjs";
import { inspectReconcileScheduler, installReconcileScheduler, removeReconcileScheduler } from "./reconcile-scheduler.mjs";
import { SCHEMA_VERSION } from "./schema.mjs";
import { openStore } from "./store.mjs";

const SRC_DIR = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(SRC_DIR, "..");
const TEMPLATE_ROOT = path.join(PACKAGE_ROOT, "templates");
const RUNTIME_VERSION = "0.7.5";

const CODEX_MARKER_START = "# agent-feedback-loop:start";
const CODEX_MARKER_END = "# agent-feedback-loop:end";

// Declarative CLI registry. Adding a new model-visible CLI = adding one entry.
// configKey/configPath are resolved against home in pathsFor.
const CLIS = [
  {
    id: "codex",
    label: "Codex",
    format: "toml",
    configKey: "codexConfig",
    configPath: [".codex", "config.toml"],
    hookEvent: "UserPromptSubmit",
    hookArgs: ["--event", "UserPromptSubmit", "--cli", "codex", "--continue"],
    stopEvent: "Stop",
    stopArgs: ["--mode", "codex"],
    hookTimeout: 5,
    stopTimeout: 5,
    timeoutUnit: "seconds"
  },
  {
    id: "claude",
    label: "Claude Code",
    format: "json",
    configKey: "claudeSettings",
    configPath: [".claude", "settings.json"],
    hookEvent: "UserPromptSubmit",
    hookArgs: ["--event", "UserPromptSubmit", "--cli", "claude"],
    stopEvent: "Stop",
    stopArgs: ["--mode", "claude"],
    hookTimeout: 5,
    stopTimeout: 5,
    timeoutUnit: "seconds"
  },
  {
    id: "gemini",
    label: "Gemini CLI",
    format: "json",
    configKey: "geminiSettings",
    configPath: [".gemini", "settings.json"],
    hookEvent: "BeforeAgent",
    hookArgs: ["--event", "BeforeAgent", "--cli", "gemini"],
    stopEvent: "AfterAgent",
    stopArgs: ["--mode", "gemini"],
    hookTimeout: 5000,
    stopTimeout: 5000,
    timeoutUnit: "milliseconds"
  }
];

export function pathsFor(home = os.homedir()) {
  const packRoot = path.join(home, ".agent", "feedback-loop");
  const runtimeRoot = path.join(packRoot, "versions", RUNTIME_VERSION);
  const dataRoot = path.join(home, ".agent", "feedback-loop-data");
  const keyRoot = path.join(home, ".agent", "feedback-loop-keys");
  const paths = {
    home,
    packRoot,
    runtimeRoot,
    runtimeLauncher: path.join(packRoot, "bin", "afl-hook"),
    runtimeCurrent: path.join(packRoot, "current.json"),
    dataRoot,
    keyRoot,
    storeFile: path.join(dataRoot, "store", "feedback-loop.sqlite3"),
    blobRoot: path.join(dataRoot, "blobs", "sha256"),
    safetyProjection: path.join(dataRoot, "safety", "guard.json.mac"),
    exportsRoot: path.join(dataRoot, "exports"),
    promptFile: path.join(packRoot, "prompts", "reflection-agent.md"),
    ruleFile: path.join(packRoot, "rules", "feedback-loop.md"),
    reviewerSchema: path.join(packRoot, "schemas", "reviewer-receipt.schema.json"),
    geminiReviewerPolicy: path.join(packRoot, "policies", "gemini-reviewer-deny-all.toml"),
    geminiReviewerSettings: path.join(packRoot, "settings", "gemini-reviewer.json"),
    reconcileLaunchAgent: path.join(home, "Library", "LaunchAgents", "io.github.super3ben.agent-feedback-loop.reconcile.plist"),
    reconcileLog: path.join(dataRoot, "logs", "reconcile.log"),
    coreHook: path.join(packRoot, "hooks", "core-hook.sh"),
    stopHook: path.join(packRoot, "hooks", "stop-hook.sh"),
    triggerRules: path.join(packRoot, "hooks", "trigger-rules.sh"),
    // Generated by older local test syncs, no longer part of the installed
    // prompt pack. Remove it on upgrade so stale tests do not reference
    // deleted per-CLI hooks.
    stalePackEntries: [
      path.join(packRoot, "tests")
    ],
    // Per-CLI hooks from <=0.1.x, replaced by the single core-hook.sh.
    // Deleted on install/uninstall so stale copies can't confuse the model.
    legacyHooks: [
      path.join(packRoot, "hooks", "codex-hook.sh"),
      path.join(packRoot, "hooks", "claude-hook.sh")
    ]
  };
  for (const cli of CLIS) {
    paths[cli.configKey] = path.join(home, ...cli.configPath);
  }
  return paths;
}

export function runtimeCapability({ nodeVersion = process.versions.node } = {}) {
  const [major, minor] = String(nodeVersion).split(".").map(Number);
  const supported = major > 24 || (major === 24 && minor >= 15);
  return {
    backend: "node:sqlite",
    minimumNode: "24.15.0",
    nodeVersion: String(nodeVersion),
    status: supported ? "configured_unverified" : "unavailable",
    reason: supported
      ? "node:sqlite backend can be checked by live doctor"
      : "Node 24.15 or newer is required for the transactional backend"
  };
}

// Full shell command a CLI config should invoke for the prompt-time hook.
function shellArgument(value) {
  return `'${String(value).replaceAll("'", `'"'"'`)}'`;
}

function hookCommand(paths, cli) {
  return [paths.coreHook, ...cli.hookArgs].map(shellArgument).join(" ");
}

// Full shell command for the post-turn backstop hook.
function stopCommand(paths, cli) {
  return [paths.stopHook, ...cli.stopArgs].map(shellArgument).join(" ");
}

function writeRuntimeLauncher(paths, dryRun, actions) {
  const target = paths.runtimeLauncher;
  actions.push(`write stable launcher -> ${target}`);
  if (dryRun) return;
  const resolver = "const fs=require('fs');const path=require('path');const current=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));const root=path.resolve(current.runtimeRoot);const versions=path.resolve(process.argv[2],'versions')+path.sep;if(!root.startsWith(versions))throw new Error('runtimeRoot is outside managed versions');process.stdout.write(root);";
  const launcher = `#!/bin/sh\nset -eu\nruntime_root="$(${JSON.stringify(process.execPath)} -e ${JSON.stringify(resolver)} ${JSON.stringify(paths.runtimeCurrent)} ${JSON.stringify(paths.packRoot)})"\nexec ${JSON.stringify(process.execPath)} "$runtime_root/bin/agent-feedback-loop.mjs" "$@"\n`;
  return mkdir(path.dirname(target), { recursive: true, mode: 0o700 })
    .then(() => writeFile(target, launcher, { mode: 0o700 }))
    .then(() => chmod(target, 0o700));
}

async function exists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function ensureSafeInstallRoot(home, directory, label, { create }) {
  const relative = path.relative(home, directory);
  if (!relative || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error(`${label} must be a child of the selected home directory`);
  }
  let current = home;
  for (const segment of relative.split(path.sep)) {
    current = path.join(current, segment);
    let info;
    try {
      info = await lstat(current);
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
      if (!create) return;
      await mkdir(current, { mode: 0o700 });
      info = await lstat(current);
    }
    if (info.isSymbolicLink()) throw new Error(`${label} path must not contain a symlink: ${current}`);
    if (!info.isDirectory()) throw new Error(`${label} path component must be a directory: ${current}`);
    if (typeof process.getuid === "function" && info.uid !== process.getuid()) {
      throw new Error(`${label} path must be owned by the current user: ${current}`);
    }
  }
  if (create) await chmod(directory, 0o700);
}

async function validateInstallRoots(paths, dryRun) {
  const options = { create: !dryRun };
  await ensureSafeInstallRoot(paths.home, paths.packRoot, "runtime root", options);
  await ensureSafeInstallRoot(paths.home, paths.dataRoot, "data root", options);
  await ensureSafeInstallRoot(paths.home, paths.keyRoot, "key root", options);
}

function timestamp() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return [
    d.getFullYear(),
    pad(d.getMonth() + 1),
    pad(d.getDate()),
    pad(d.getHours()),
    pad(d.getMinutes()),
    pad(d.getSeconds())
  ].join("");
}

async function backup(file, dryRun, actions) {
  if (!(await exists(file))) return null;
  const target = `${file}.backup-${timestamp()}`;
  actions.push(`backup ${file} -> ${target}`);
  if (!dryRun) await copyFile(file, target);
  return target;
}

function tomlString(value) {
  return JSON.stringify(value);
}

function removeMarkedCodexBlock(text) {
  const lines = text.split(/\r?\n/);
  const kept = [];
  let skipping = false;
  for (const line of lines) {
    if (line.trim() === CODEX_MARKER_START) {
      skipping = true;
      continue;
    }
    if (line.trim() === CODEX_MARKER_END) {
      skipping = false;
      continue;
    }
    if (!skipping) kept.push(line);
  }
  return kept.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd();
}

function removeUnmarkedLegacyCodexBlocks(text) {
  const lines = text.split(/\r?\n/);
  const chunks = [];
  let current = [];
  const isTopLevelHook = (line) => /^\s*\[\[hooks\.[^.\]]+\]\]\s*$/.test(line);
  for (const line of lines) {
    if (isTopLevelHook(line) && current.length > 0) {
      chunks.push(current);
      current = [];
    }
    current.push(line);
  }
  if (current.length > 0) chunks.push(current);
  return chunks
    .filter((chunk) => !/(?:codex|claude)-hook\.sh/.test(chunk.join("\n")))
    .flat()
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();
}

function codexHookBlock(paths, cli) {
  return [
    CODEX_MARKER_START,
    `[[hooks.${cli.hookEvent}]]`,
    "",
    `[[hooks.${cli.hookEvent}.hooks]]`,
    'type = "command"',
    `command = ${tomlString(hookCommand(paths, cli))}`,
    `timeout = ${cli.hookTimeout}`,
    'statusMessage = "Injecting feedback reflection prompt"',
    "",
    `[[hooks.${cli.stopEvent}]]`,
    "",
    `[[hooks.${cli.stopEvent}.hooks]]`,
    'type = "command"',
    `command = ${tomlString(stopCommand(paths, cli))}`,
    `timeout = ${cli.stopTimeout}`,
    'statusMessage = "Checking feedback reflection backstop"',
    CODEX_MARKER_END
  ].join("\n");
}

// Remove our managed entries for a given JSON-config CLI (Claude/Gemini).
// Cleans both the prompt-time hook (hookEvent) and the backstop (stopEvent),
// matching our hook paths plus legacy per-CLI hook commands.
function removeJsonHookEntries(settings, paths, cli) {
  const isOurs = (hook) => {
    const command = typeof hook.command === "string" ? hook.command : "";
    const prompt = typeof hook.prompt === "string" ? hook.prompt : "";
    return command.includes(paths.coreHook)
      || command.includes(paths.stopHook)
      || command.includes("codex-hook.sh")
      || command.includes("claude-hook.sh")
      || prompt.includes(paths.promptFile);
  };
  for (const event of [cli.hookEvent, cli.stopEvent]) {
    const hooks = settings.hooks?.[event];
    if (!Array.isArray(hooks)) continue;
    settings.hooks[event] = hooks
      .map((entry) => {
        if (!entry || !Array.isArray(entry.hooks)) return entry;
        return { ...entry, hooks: entry.hooks.filter((hook) => !isOurs(hook)) };
      })
      .filter((entry) => !entry || !Array.isArray(entry.hooks) || entry.hooks.length > 0);
  }
  return settings;
}

async function readJsonSettings(file) {
  if (!(await exists(file))) return {};
  const text = await readFile(file, "utf8");
  if (!text.trim()) return {};
  return JSON.parse(text);
}

async function removeLegacyHooks(paths, dryRun, actions) {
  for (const file of paths.legacyHooks) {
    if (!(await exists(file))) continue;
    actions.push(`remove legacy hook ${file}`);
    if (!dryRun) await rm(file, { force: true });
  }
}

async function removeStalePromptPackEntries(paths, dryRun, actions) {
  for (const entry of paths.stalePackEntries) {
    if (!(await exists(entry))) continue;
    actions.push(`remove stale tests ${entry}`);
    if (!dryRun) await rm(entry, { recursive: true, force: true });
  }
}

async function writePromptPack(paths, dryRun, actions) {
  actions.push(`copy templates -> ${paths.packRoot}`);
  if (dryRun) {
    await removeStalePromptPackEntries(paths, dryRun, actions);
    await removeLegacyHooks(paths, dryRun, actions);
    return;
  }
  await mkdir(path.dirname(paths.packRoot), { recursive: true });
  await cp(TEMPLATE_ROOT, paths.packRoot, { recursive: true });
  await mkdir(paths.runtimeRoot, { recursive: true, mode: 0o700 });
  await chmod(paths.runtimeRoot, 0o700);
  await cp(path.join(PACKAGE_ROOT, "bin"), path.join(paths.runtimeRoot, "bin"), { recursive: true });
  await cp(path.join(PACKAGE_ROOT, "src"), path.join(paths.runtimeRoot, "src"), { recursive: true });
  await chmod(path.join(paths.runtimeRoot, "bin", "agent-feedback-loop.mjs"), 0o755);
  await mkdir(paths.dataRoot, { recursive: true, mode: 0o700 });
  await chmod(paths.dataRoot, 0o700);
  await mkdir(paths.keyRoot, { recursive: true, mode: 0o700 });
  await chmod(paths.keyRoot, 0o700);
  await mkdir(path.dirname(paths.runtimeCurrent), { recursive: true, mode: 0o700 });
  const currentPayload = `${JSON.stringify({
    runtimeVersion: RUNTIME_VERSION,
    runtimeRoot: paths.runtimeRoot,
    schemaVersion: SCHEMA_VERSION,
    capability: runtimeCapability(),
    installedAt: new Date().toISOString()
  }, null, 2)}\n`;
  const currentTemp = `${paths.runtimeCurrent}.${process.pid}.${Date.now()}.tmp`;
  await writeFile(currentTemp, currentPayload, { mode: 0o600, flag: "wx" });
  await chmod(currentTemp, 0o600);
  await rename(currentTemp, paths.runtimeCurrent);
  await chmod(paths.runtimeCurrent, 0o600);
  await chmod(paths.coreHook, 0o755);
  await chmod(paths.stopHook, 0o755);
  await removeStalePromptPackEntries(paths, dryRun, actions);
  // cp does not delete files absent from templates, so pre-0.2 per-CLI hooks
  // linger after an upgrade. Remove them explicitly.
  await removeLegacyHooks(paths, dryRun, actions);
}

async function installTomlBlock(paths, cli, dryRun, actions) {
  const configFile = paths[cli.configKey];
  await backup(configFile, dryRun, actions);
  const current = (await exists(configFile)) ? await readFile(configFile, "utf8") : "";
  const cleaned = removeUnmarkedLegacyCodexBlocks(removeMarkedCodexBlock(current));
  const block = codexHookBlock(paths, cli);
  const next = `${cleaned.trimEnd()}${cleaned.trim() ? "\n\n" : ""}${block}\n`;
  actions.push(`connect ${cli.label} hook -> ${paths.coreHook}`);
  if (!dryRun) {
    await mkdir(path.dirname(configFile), { recursive: true });
    await writeFile(configFile, next, "utf8");
  }
}

async function installJsonHooks(paths, cli, dryRun, actions) {
  const configFile = paths[cli.configKey];
  await backup(configFile, dryRun, actions);
  const settings = removeJsonHookEntries(await readJsonSettings(configFile), paths, cli);
  settings.hooks = settings.hooks || {};
  settings.hooks[cli.hookEvent] = settings.hooks[cli.hookEvent] || [];
  settings.hooks[cli.hookEvent].push({
    matcher: "",
    hooks: [{ type: "command", command: hookCommand(paths, cli), timeout: cli.hookTimeout }]
  });
  settings.hooks[cli.stopEvent] = settings.hooks[cli.stopEvent] || [];
  settings.hooks[cli.stopEvent].push({
    matcher: "",
    hooks: [{ type: "command", command: stopCommand(paths, cli), timeout: cli.stopTimeout }]
  });
  actions.push(`connect ${cli.label} hook -> ${paths.coreHook}`);
  actions.push(`connect ${cli.label} backstop -> ${paths.stopHook}`);
  if (!dryRun) {
    await mkdir(path.dirname(configFile), { recursive: true });
    await writeFile(configFile, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
  }
}

async function installCli(paths, cli, dryRun, actions) {
  if (cli.format === "toml") {
    await installTomlBlock(paths, cli, dryRun, actions);
  } else {
    await installJsonHooks(paths, cli, dryRun, actions);
  }
}

export async function install(options = {}) {
  const home = options.home || os.homedir();
  const dryRun = Boolean(options.dryRun);
  const capability = runtimeCapability({ nodeVersion: options.nodeVersion || process.versions.node });
  if (capability.status === "unavailable") throw new Error(capability.reason);
  const paths = pathsFor(home);
  const actions = [];
  await validateInstallRoots(paths, dryRun);
  await writePromptPack(paths, dryRun, actions);
  await writeRuntimeLauncher(paths, dryRun, actions);
  for (const cli of CLIS) {
    await installCli(paths, cli, dryRun, actions);
  }
  const scheduler = await installReconcileScheduler({
    paths,
    platform: options.platform || process.platform,
    dryRun,
    activate: options.activateScheduler ?? (!dryRun && path.resolve(home) === path.resolve(os.homedir())),
    host: options.schedulerHost,
    intervalSeconds: Number(options.reconcileIntervalSeconds || 60)
  });
  if (scheduler.supported) {
    actions.push(`configure Codex transcript reconciliation every 60s -> ${paths.reconcileLaunchAgent}`);
    if (scheduler.active) actions.push("start Codex transcript reconciliation scheduler");
  } else {
    actions.push("Codex transcript reconciliation scheduler unavailable on this platform; model-visible hooks remain enabled");
  }
  let codex = { available: false, configured: dryRun, runnable: false, status: dryRun ? "dry_run" : "unavailable" };
  if (!dryRun) {
    const cli = CLIS.find((entry) => entry.id === "codex");
    const codexHost = options.codexHost || createCodexHost({ version: RUNTIME_VERSION });
    codex = await codexHost.synchronize({
      home,
      cwd: options.cwd || process.cwd(),
      promptCommand: hookCommand(paths, cli),
      backstopCommand: stopCommand(paths, cli)
    });
    if (codex.runnable) {
      actions.push(`Codex hooks verified for a newly spawned app-server via ${codex.hostCommand || "host inspector"}; already-running Desktop tasks are covered by transcript reconciliation`);
    } else {
      actions.push(`Codex hooks configured but not runnable (${codex.status}${codex.reason ? `: ${codex.reason}` : ""})`);
    }
  }
  return { dryRun, paths, actions, codex, scheduler };
}

async function uninstallCli(paths, cli, dryRun, actions) {
  const configFile = paths[cli.configKey];
  if (!(await exists(configFile))) return;
  await backup(configFile, dryRun, actions);
  if (cli.format === "toml") {
    const current = await readFile(configFile, "utf8");
    const next = `${removeUnmarkedLegacyCodexBlocks(removeMarkedCodexBlock(current))}\n`;
    actions.push(`disconnect ${cli.label} hook`);
    if (!dryRun) await writeFile(configFile, next, "utf8");
  } else {
    const settings = removeJsonHookEntries(await readJsonSettings(configFile), paths, cli);
    actions.push(`disconnect ${cli.label} hook`);
    if (!dryRun) await writeFile(configFile, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
  }
}

export async function uninstall(options = {}) {
  const home = options.home || os.homedir();
  const dryRun = Boolean(options.dryRun);
  const removeFiles = Boolean(options.removeFiles);
  const paths = pathsFor(home);
  const actions = [];

  for (const cli of CLIS) {
    await uninstallCli(paths, cli, dryRun, actions);
  }
  const scheduler = await removeReconcileScheduler({
    paths,
    platform: options.platform || process.platform,
    dryRun,
    activate: options.activateScheduler ?? (!dryRun && path.resolve(home) === path.resolve(os.homedir())),
    host: options.schedulerHost
  });
  if (scheduler.supported) actions.push(`remove Codex transcript reconciliation scheduler ${paths.reconcileLaunchAgent}`);

  if (removeFiles) {
    actions.push(`remove ${paths.packRoot}`);
    if (!dryRun) {
      await rm(paths.packRoot, { recursive: true, force: true });
      await rm(paths.runtimeRoot, { recursive: true, force: true });
    }
  } else {
    await removeLegacyHooks(paths, dryRun, actions);
  }

  return { dryRun, paths, actions, scheduler };
}

async function isExecutable(file) {
  try {
    await access(file, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

export async function doctor(options = {}) {
  const home = options.home || os.homedir();
  const paths = pathsFor(home);

  const files = {
    prompt: await exists(paths.promptFile),
    rule: await exists(paths.ruleFile),
    runtimeLauncher: await exists(paths.runtimeLauncher),
    runtimeCurrent: await exists(paths.runtimeCurrent),
    coreHook: await exists(paths.coreHook),
    stopHook: await exists(paths.stopHook),
    triggerRules: await exists(paths.triggerRules),
    coreHookExecutable: await isExecutable(paths.coreHook),
    stopHookExecutable: await isExecutable(paths.stopHook)
  };
  let runtime = { selected: false, expectedVersion: RUNTIME_VERSION, expectedSchemaVersion: SCHEMA_VERSION };
  try {
    const current = JSON.parse(await readFile(paths.runtimeCurrent, "utf8"));
    runtime = {
      ...runtime,
      selected: current.runtimeVersion === RUNTIME_VERSION
        && path.resolve(current.runtimeRoot) === path.resolve(paths.runtimeRoot)
        && Number(current.schemaVersion) === SCHEMA_VERSION,
      runtimeVersion: current.runtimeVersion,
      runtimeRoot: current.runtimeRoot,
      schemaVersion: current.schemaVersion
    };
  } catch (error) {
    runtime.reason = error.message;
  }
  files.runtimeSelected = runtime.selected;

  const clis = {};
  for (const cli of CLIS) {
    const configFile = paths[cli.configKey];
    if (cli.format === "toml") {
      const text = (await exists(configFile)) ? await readFile(configFile, "utf8") : "";
      const promptConnected = text.includes(paths.coreHook);
      const backstopConnected = text.includes(paths.stopHook);
      const configured = promptConnected && backstopConnected;
      const codexHost = options.codexHost || createCodexHost({ version: RUNTIME_VERSION });
      const host = await codexHost.inspect({
        home,
        cwd: options.cwd || process.cwd(),
        promptCommand: hookCommand(paths, cli),
        backstopCommand: stopCommand(paths, cli)
      });
      const runnable = configured && host.runnable;
      clis[cli.id] = {
        connected: runnable,
        configured,
        runnable,
        promptConnected: configured && Boolean(host.prompt?.runnable),
        backstopConnected: configured && Boolean(host.backstop?.runnable),
        promptConfigured: promptConnected,
        backstopConfigured: backstopConnected,
        promptTrustStatus: host.prompt?.trustStatus || "unknown",
        backstopTrustStatus: host.backstop?.trustStatus || "unknown",
        status: host.status,
        hostAvailable: host.available,
        hostCommand: host.hostCommand,
        inspectionScope: host.inspectionScope || "spawned_app_server",
        activeDesktopState: host.activeDesktopState || "not_observed",
        reason: host.reason,
        managedBlock: text.includes(CODEX_MARKER_START)
      };
    } else {
      let settings = {};
      try {
        settings = await readJsonSettings(configFile);
      } catch {
        settings = {};
      }
      const cmds = (event) => (Array.isArray(settings.hooks?.[event])
        ? settings.hooks[event].flatMap((entry) => (Array.isArray(entry.hooks) ? entry.hooks : []))
        : []).map((hook) => (typeof hook.command === "string" ? hook.command : ""));
      const promptConnected = cmds(cli.hookEvent).some((c) => c.includes(paths.coreHook));
      const backstopConnected = cmds(cli.stopEvent).some((c) => c.includes(paths.stopHook));
      clis[cli.id] = {
        connected: promptConnected && backstopConnected,
        configured: promptConnected && backstopConnected,
        runnable: promptConnected && backstopConnected,
        promptConnected,
        backstopConnected
      };
    }
  }

  const capability = runtimeCapability();
  const scheduler = await inspectReconcileScheduler({
    paths,
    platform: options.platform || process.platform,
    host: options.schedulerHost
  });
  let reconciliation = { status: "not_run" };
  if (await exists(paths.storeFile)) {
    try {
      const store = openStore({ paths });
      reconciliation = store.getRuntimeStatus("codex_reconcile") || reconciliation;
      store.close();
    } catch (error) {
      reconciliation = { status: "unavailable", reason: error.message };
    }
  }
  const reviewerDetector = options.reviewerDetector || detectAllReviewerAdapters;
  const reviewers = await reviewerDetector();
  const readyClis = [];
  const unavailableClis = [];
  for (const cli of CLIS) {
    const reviewer = reviewers[cli.id] || { cli: cli.id, available: false, executable: null };
    const operational = Boolean(clis[cli.id].runnable && reviewer.available);
    clis[cli.id] = {
      ...clis[cli.id],
      reviewerAvailable: Boolean(reviewer.available),
      reviewerExecutable: reviewer.executable || reviewer.command || null,
      operational
    };
    if (operational) readyClis.push(cli.id);
    else unavailableClis.push(cli.id);
  }
  const schedulerRequired = options.requireScheduler ?? (scheduler.supported && path.resolve(home) === path.resolve(os.homedir()));
  const schedulerReady = !schedulerRequired || Boolean(scheduler.configured && scheduler.active);
  const reconciliationFreshnessMs = Math.max(60_000, Number(options.reconciliationFreshnessMs || 5 * 60 * 1000));
  const reconciliationUpdatedAt = Date.parse(reconciliation.updatedAt || "");
  const reconciliationFresh = Number.isFinite(reconciliationUpdatedAt)
    && Date.now() - reconciliationUpdatedAt <= reconciliationFreshnessMs;
  const reconciliationSuccessful = reconciliation.status === "completed";
  const reconciliationReady = !schedulerRequired || (reconciliationSuccessful && reconciliationFresh);
  scheduler.required = Boolean(schedulerRequired);
  reconciliation.fresh = reconciliationFresh;
  reconciliation.ready = reconciliationReady;
  const healthy = Object.values(files).every(Boolean)
    && CLIS.every((cli) => clis[cli.id].runnable)
    && schedulerReady
    && reconciliationReady
    && readyClis.length > 0;
  const degraded = reconciliation.status === "completed_with_errors" || unavailableClis.length > 0;
  return {
    healthy,
    degraded,
    home,
    files,
    runtime,
    clis,
    scheduler,
    reconciliation,
    reviewers,
    operational: { readyClis, unavailableClis, schedulerReady, reconciliationReady },
    capability,
    dataRoot: paths.dataRoot,
    keyRoot: paths.keyRoot
  };
}

export async function assertTemplateTree() {
  await stat(TEMPLATE_ROOT);
}
